language: go
go: 1.9
sudo: true # give us 7.5GB and >2 bursted cores.
branches:
  only:
  - master
before_install:
    - export PULUMI_ROOT=/opt/pulumi
    # Install Docker 17.09.
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    - sudo apt-get update
    - sudo apt-get -y install docker-ce=17.09.0~ce-0~ubuntu
    - docker version
    # Dep for Go dependency management.
    - go get -v github.com/golang/dep/cmd/dep
    # Node.js 6.10.2 for Pulumi Fabric's Node.js runtime.
    - nvm install v6.10.2
    # Install the AWS CLI so that we can publish the resulting release (if applicable) at the end.
    - pip install --upgrade --user awscli
    # Install Yarn as per https://yarnpkg.com/lang/en/docs/install-ci/#travis-tab.
    - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.2.1
    - export PATH=$HOME/.yarn/bin:$PATH
install:
    # Clone the Pulumi repo and use its script to fetch the latest installation packages.
    - git clone git@github.com:pulumi/home ${GOPATH}/src/github.com/pulumi/home
    - ${GOPATH}/src/github.com/pulumi/home/scripts/install-locked.sh ${PULUMI_ROOT} pulumi pulumi-aws
    - make ensure
script:
    # Configure the environment s.t. Terraform panics on schema errors in order to aid debugging and Terraform tracing
    # is enabled.
    - export TF_SCHEMA_PANIC_ON_ERROR=true
    - export TF_LOG=TRACE
    - make travis_${TRAVIS_EVENT_TYPE}
notifications:
    webhooks: https://ufci1w66n3.execute-api.us-west-2.amazonaws.com/stage/travis
